### ISSUE TITLE
Missing Build Instructions

### ISSUE THREAD

**Issue by umbeebmu** [pudkipz/slide_game#7]
Hi
Could you please add some instructions on how to build and run the project?
Which java version is required? 
Which additional libraries are needed? (javafx?) 

Thanks

**Comment by pudkipz** [comment]
Build instructions added in readme. Is there still anything missing?

**Comment by umbeebmu** [comment]
Thanks for the update.
After numerous attempt,at last I managed to compile/run it from command line on Ubuntu 18.10 with the following:
Install java jdk8 (this is the last one that includes javafx) using the instructions: https://websiteforstudents.com/how-to-install-oracle-java-jdk8-on-ubuntu-16-04-17-10-18-04-desktops/
compile with: javac -d . src/*.java
run with: java GameGUI
